version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    ports:
      - "${WEBHOOK_PORT:-8080}:${WEBHOOK_PORT:-8080}"
    restart: always
    volumes:
      - db_data:/app

volumes:
  db_data:
