version: '3.8'

services:
  bot:
    build: .
    container_name: t-c-tg-bot_bot
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    ports:
      - "${WEBHOOK_PORT:-8080}:${WEBHOOK_PORT:-8080}"
    restart: always
    volumes:
      - db_data:/app

volumes:
  db_data:
